export const mockedList = [
  {
    id: 1,
    title: 'string',
    overview: 'string',
    release_date: 'string',
    vote_average: 1.2,
    vote_count: 123,
    poster_path: 'string',
    backdrop_path: 'string',
    genre_ids: [12],
    original_language: 'string',
    original_title: 'string',
    popularity: 3,
    video: false,
    adult: false,
  },
  {
    id: 1,
    title: 'string',
    overview: 'string',
    release_date: 'string',
    vote_average: 1.2,
    vote_count: 123,
    poster_path: 'string',
    backdrop_path: 'string',
    genre_ids: [12],
    original_language: 'string',
    original_title: 'string',
    popularity: 3,
    video: false,
    adult: false,
  },
  {
    id: 1,
    title: 'string',
    overview: 'string',
    release_date: 'string',
    vote_average: 1.2,
    vote_count: 123,
    poster_path: 'string',
    backdrop_path: 'string',
    genre_ids: [12],
    original_language: 'string',
    original_title: 'string',
    popularity: 3,
    video: false,
    adult: false,
  },
  {
    id: 1,
    title: 'string',
    overview: 'string',
    release_date: 'string',
    vote_average: 1.2,
    vote_count: 123,
    poster_path: 'string',
    backdrop_path: 'string',
    genre_ids: [12],
    original_language: 'string',
    original_title: 'string',
    popularity: 3,
    video: false,
    adult: false,
  },
  {
    id: 1,
    title: 'string',
    overview: 'string',
    release_date: 'string',
    vote_average: 1.2,
    vote_count: 123,
    poster_path: 'string',
    backdrop_path: 'string',
    genre_ids: [12],
    original_language: 'string',
    original_title: 'string',
    popularity: 3,
    video: false,
    adult: false,
  },
  {
    id: 1,
    title: 'string',
    overview: 'string',
    release_date: 'string',
    vote_average: 1.2,
    vote_count: 123,
    poster_path: 'string',
    backdrop_path: 'string',
    genre_ids: [12],
    original_language: 'string',
    original_title: 'string',
    popularity: 3,
    video: false,
    adult: false,
  },
]
